- name: Deploy MERN App
  hosts: servers
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Pull latest Docker images
      shell: |
        docker pull prernadocker09876/frontend-app:latest
        docker pull prernadocker09876/backend-app:latest

    - name: Run frontend container
      shell: |
        docker run -d -p 5173:5173 --name frontend-app prernadocker09876/frontend-app:latest

    - name: Run backend container
      shell: |
        docker run -d -p 5000:5000 --name backend-app prernadocker09876/backend-app:latest
